
//   import "./items/name"
//   import "./blocks/name"
//   import "./api/name"

import "./items/wrench.js"
import "./blocks/creative_battery.js"
import "./blocks/blockDatas.js"
import "./blocks/enegry_cable.js"
import "./blocks/solarPenal"
import "./blocks/harvestor"
import "./blocks/chestui"
//import "./um/target"
import "./blocks/treeCutter"
import "./blocks/common"
import "./blocks/itemCollector"
import "./blocks/alloy_smelter"

import "./api/Fluid"
import "./api/Energy"
import "./api/Manager"